<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PriyankasLaptop" failures="3" tests="4" name="Test" time="2.209" errors="0" timestamp="2024-05-26T19:56:29 PDT">
  <testcase classname="api.test.UserTests" name="testPostUser" time="0.957"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="0.375">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;500&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<500> but was:<200>
at api.test.UserTests.testGetUserByName(UserTests.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests" name="updateUserByName" time="0.387">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;500&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<500> but was:<200>
at api.test.UserTests.updateUserByName(UserTests.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- updateUserByName -->
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="0.389">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;500&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<500> but was:<200>
at api.test.UserTests.testDeleteUserByName(UserTests.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- Test -->
